## Lecture 7: Numpy

In [1]:
import numpy as np

In [3]:
array_1 = np.array([1,2,3,4])
type(array_1)

numpy.ndarray

In [4]:
print(array_1)

[1 2 3 4]


In [8]:
arr2 =np.array([1,3.14,2],dtype=np.int32)
arr2.dtype

dtype('int32')

In [9]:
arr2

array([1, 3, 2], dtype=int32)

In [32]:
arr3 = np.zeros(10000000, dtype=np.float64)
arr4 = np.zeros(10000000, dtype=np.int8)
print(arr3.dtype)
print(arr4.dtype)

float64
int8


In [29]:
print(arr3.nbytes)
print(arr4.nbytes)

80000000
10000000


In [34]:
np.random.seed(0) # seed for reproducibility
x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array 


In [35]:
x1.ndim 

1

In [36]:
x2.ndim

2

In [37]:
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [38]:
print(x3)

[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [39]:
x3.ndim 

3

In [40]:
x1.shape

(6,)

In [41]:
x2.shape

(3, 4)

In [42]:
x3.shape

(3, 4, 5)

In [44]:
print(x1)
x1.size 

[5 0 3 3 7 9]


6

In [45]:
len(x1)

6

In [46]:
print(x2.size, len(x2))

12 3


In [47]:
x2.shape

(3, 4)

In [48]:
x1[1]

np.int32(0)

In [49]:
x1[:2]

array([5, 0], dtype=int32)

In [52]:
np.random.seed(0) # seed for reproducibility
x1 = np.random.randint(10, size=6) # One-dimensional array
print(x1)
x1[0] = 3.14
print(x1)

[5 0 3 3 7 9]
[3 0 3 3 7 9]


In [53]:
x2[1][3]

np.int32(8)

In [54]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]], dtype=int32)

In [58]:
x2_sub = x2[:2,:3]
print(x2_sub)
x2_sub[0,0] = 999
print(x2)
print(x2_sub)

[[3 5 2]
 [7 6 8]]
[[999   5   2   4]
 [  7   6   8   8]
 [  1   6   7   7]]
[[999   5   2]
 [  7   6   8]]


In [59]:
# Tạo một mảng NumPy lớn 
arr = np.arange(1e6) 
# Sử dụng hàm tổng hợp của NumPy 
%timeit np.sum(arr) 
# Sử dụng hàm tích hợp sẵn của Python 
%timeit sum(arr) 


1.8 ms ± 53.7 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
85.6 ms ± 2.27 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [61]:
x2

array([[999,   5,   2,   4],
       [  7,   6,   8,   8],
       [  1,   6,   7,   7]], dtype=int32)

In [64]:
x2[x2%2==0].sum()

np.int64(34)

In [66]:
x3[x3%2==0]

array([8, 8, 4, 0, 0, 2, 8, 0, 0, 4, 2, 2, 0, 0, 4, 6, 8, 4, 4, 8, 6, 2,
       0, 4, 4, 6, 4], dtype=int32)

In [69]:
np.sum(x2>8)>0

np.True_