## Lecture 7: Numpy

In [1]:
import numpy as np

In [3]:
array_1 = np.array([1,2,3,4])
type(array_1)

numpy.ndarray

In [4]:
print(array_1)

[1 2 3 4]


In [8]:
arr2 =np.array([1,3.14,2],dtype=np.int32)
arr2.dtype

dtype('int32')

In [9]:
arr2

array([1, 3, 2], dtype=int32)

In [32]:
arr3 = np.zeros(10000000, dtype=np.float64)
arr4 = np.zeros(10000000, dtype=np.int8)
print(arr3.dtype)
print(arr4.dtype)

float64
int8


In [29]:
print(arr3.nbytes)
print(arr4.nbytes)

80000000
10000000


In [34]:
np.random.seed(0) # seed for reproducibility
x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array 


In [35]:
x1.ndim 

1

In [36]:
x2.ndim

2

In [37]:
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [38]:
print(x3)

[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [39]:
x3.ndim 

3

In [40]:
x1.shape

(6,)

In [41]:
x2.shape

(3, 4)

In [42]:
x3.shape

(3, 4, 5)

In [44]:
print(x1)
x1.size 

[5 0 3 3 7 9]


6

In [45]:
len(x1)

6

In [46]:
print(x2.size, len(x2))

12 3


In [47]:
x2.shape

(3, 4)

In [48]:
x1[1]

np.int32(0)

In [49]:
x1[:2]

array([5, 0], dtype=int32)

In [52]:
np.random.seed(0) # seed for reproducibility
x1 = np.random.randint(10, size=6) # One-dimensional array
print(x1)
x1[0] = 3.14
print(x1)

[5 0 3 3 7 9]
[3 0 3 3 7 9]


In [53]:
x2[1][3]

np.int32(8)

In [54]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]], dtype=int32)

In [58]:
x2_sub = x2[:2,:3]
print(x2_sub)
x2_sub[0,0] = 999
print(x2)
print(x2_sub)

[[3 5 2]
 [7 6 8]]
[[999   5   2   4]
 [  7   6   8   8]
 [  1   6   7   7]]
[[999   5   2]
 [  7   6   8]]


In [59]:
# Tạo một mảng NumPy lớn 
arr = np.arange(1e6) 
# Sử dụng hàm tổng hợp của NumPy 
%timeit np.sum(arr) 
# Sử dụng hàm tích hợp sẵn của Python 
%timeit sum(arr) 


1.8 ms ± 53.7 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
85.6 ms ± 2.27 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [61]:
x2

array([[999,   5,   2,   4],
       [  7,   6,   8,   8],
       [  1,   6,   7,   7]], dtype=int32)

In [64]:
x2[x2%2==0].sum()

np.int64(34)

In [66]:
x3[x3%2==0]

array([8, 8, 4, 0, 0, 2, 8, 0, 0, 4, 2, 2, 0, 0, 4, 6, 8, 4, 4, 8, 6, 2,
       0, 4, 4, 6, 4], dtype=int32)

In [69]:
np.sum(x2>8)>0

np.True_

In [1]:
import numpy as np 

In [22]:
np.random.seed(0)
x = np.random.randint(2,40,(80,90))
x 

array([[ 2,  5,  5, ..., 31,  5, 36],
       [15, 23, 11, ..., 39, 30,  4],
       [29, 21, 27, ...,  9, 25, 15],
       ...,
       [29, 37,  3, ...,  7, 11, 25],
       [22, 29, 31, ..., 37,  5, 11],
       [20,  7, 28, ..., 17, 22, 12]], dtype=int32)

In [23]:
from my_module_1 import is_prime

In [24]:
def sum_primes(x):
    s = 0
    size = x.shape
    for i in range(size[0]):
        for j in range(size[1]):
            if is_prime(x[i,j]):
                s += x[i,j]
    return s 

In [25]:
%timeit sum_primes(x) 

21.7 ms ± 2.41 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [28]:
%timeit x.flatten()[list(map(is_prime, x.flatten()))].sum()

17.8 ms ± 777 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [41]:
np.sum(x<6,axis=1)

array([15, 15, 10,  7,  9, 11, 12,  7,  8, 10, 10, 10,  8, 10,  6, 10,  9,
        8,  9, 10,  8,  8,  7,  3,  9,  8,  8, 14, 17, 14, 10, 12, 13, 11,
       13,  9,  9, 12, 11,  9, 16,  8,  7, 10,  8, 13,  6,  8,  9,  9, 11,
        7,  9, 13, 15, 12,  9,  9,  7,  4, 10, 12,  8, 12,  6, 11, 13,  6,
        9,  9,  3, 16,  9, 11,  9,  7,  5,  7, 11,  8])

In [42]:
np.sum(x<6,axis=1).shape

(80,)

In [34]:
x.shape

(80, 90)

In [36]:
arr1 = np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6]])
arr1 

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [38]:
np.sum(arr1, axis=0)

array([ 6,  9, 12, 15])

In [39]:
np.sum(arr1, axis=1)

array([10, 14, 18])